### ISSUE TITLE
F3800 set up failing

### ISSUE THREAD

**Issue by LouPaloma** [flip-dots/HaSolixBLE#50]
I'm running a F3800 with firmware version 2.7.2.  I have successfully added the device, but no sensors are being created.  Reloading the integration produces the same errors as noted in the log snippet below.  Perhaps exception handling is too coarse grained such that a single failure kills the entire process?

```
2026-09-12 14:12:32.411 INFO (MainThread) [homeassistant.components.sensor] Setting up solix_ble.sensor
2026-09-12 14:12:32.412 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up solix_ble platform for sensor: 'F3800' object has no attribute 'power_in'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/solix_ble/sensor.py", line 251, in async_setup_entry
    SolixSensorEntity(
    ~~~~~~~~~~~~~~~~~^
        device, "Total Power In", "W", "power_in", SensorDeviceClass.POWER
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/solix_ble/sensor.py", line 1220, in __init__
    self._update_updatable_attributes()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solix_ble/sensor.py", line 1234, in _update_updatable_attributes
    attribute_value = getattr(self._device, self._attribute_name)
AttributeError: 'F3800' object has no attribute 'power_in'. Did you mean: 'ac_power_in'?
2026-09-12 14:12:32.415 INFO (MainThread) [homeassistant.components.switch] Setting up solix_ble.switch
```

**Comment by flip-dots** [comment]
This is a known issue #28 #47 and is addressed in [v3.7.0 Beta 1](https://github.com/flip-dots/HaSolixBLE/releases/tag/v3.7.0-b1). Please let me know if the issue is still present in the pre-release.

**Comment by mboisson** [comment]
wow... just wow. I decide to try to connect my F3800 Plus this morning and I stumbled onto this... and it just works with 3.7.0 beta 1. 

<img width="395" height="508" alt="Image" src="https://github.com/user-attachments/assets/4ae7f183-282b-4e56-b8b4-d4a5ae856db7" />
<img width="397" height="774" alt="Image" src="https://github.com/user-attachments/assets/8aa75ed0-f10e-4634-a7d1-94f352b4eb79" />

One thing it does not seem to relay is the total capacity and the expansion battery status. Do you know if it's possible to do that ?

**Comment by mboisson** [comment]
I confirm that it controls the AC output switch. I am not sure if it controls the DC output switch, as I do not have anything plugged in DC and if I switch it on, it switches back off (maybe because nothing is plugged in).

**Comment by mboisson** [comment]
Do you think it would be possible to control the max generator input setting on the F3800+ ? That's a setting we have in the Anker app.

**Comment by LouPaloma** [comment]
I can confirm that my F3800 is now able to connect using the beta.1   I'm deferring closing the issue in case you want it for tracking until the next release candidate.
